### ISSUE TITLE
Comment in "Correlation" Section of Large N chapter

### ISSUE THREAD

**Issue by chrisdaaz** [nulib-oer/empirical-methods-polisci#7]
There is a part within the text that is commented out (emphasis added):

>Simple correlations are not as often found in recent scholarship as regression, mostly because regression is far more powerful and flexible than correlation, and hardly more difficult to calculate. Still, as noted above, correlations can be useful for an initial look at the data and when describing data. **\<\!\-\- Take @whitakerExplainingSupportUK2011, who are trying to understand the success of the UK Independence Party at the 2009 European Parliament Election. The first thing they do is simply to see whether support for UKIP correlates with support for the conservative or labour parties in the same geographical area, before moving on to a more sophisticated regression that relates support for UKIP to a number of demographic factors.\-\-\>**

Should this be deleted, or uncommented? @mweylandt 

https://github.com/nulib-oer/empirical-methods-polisci/blob/a998253a8a683363ff2a2286d0cd699098f1e463/08-large-n.Rmd#L158

**Comment by mweylandt** [comment]
This is a great question. I actually don't remember why I took it out - word limit, or because I had struggles with the citation? Looking at it now I'm happy to have it included in the text.
